### ISSUE TITLE
Error when trying to use the script for the analysis of a single sample

### ISSUE THREAD

**Issue by hamzaaitabbou96** [athalexiou/DIANA-mAP#1]
Hi

Thank you for this awesome work. I have been working with your tool for my research. But, I am facing a bit of trouble when trying to use the script for the analysis of a single sample.

When i use this command :
`Rscript diana_map.r -e 'experiment_1' -j 2 -l 16 /home/SRR033731/SRR033731.fastq /home/results/`

I get the following error :
![er_intance1](https://user-images.githubusercontent.com/65475732/106163542-939ebe00-6189-11eb-9258-603a24bd0393.JPG)

Any ideas what is the problem?

**Comment by athalexiou** [comment]
Hello,

During the pre-processing step the DNApi tool's "exhaustive mode" is used for automated adapter inference. In that mode, each potential adapter is trimmed from the sample and the remaining reads are mapped in the reference genome in order to use the mapping percentage as an indication for the adapter inference process.

In your error, it seems that this mapping process is failed which probably has something to do with the reference genome provided.

Make sure that you have provided the correct directory and prefix of your reference genome index inside the diana_map_config.r file and if the extension of your index files is ".ebwt" set the large_index parameter to FALSE. The reference genome index must be created using Bowtie1 , more information on that can be found on the Bowtie manual.
