### ISSUE TITLE
Error in master_table

### ISSUE THREAD

**Issue by RNJ1993** [athalexiou/DIANA-mAP#2]
Hi, I have run DIANA_mAP with the following command on my local Docker:

Rscript diana_map_multi.r -d /home/DIANA_mAP/example_DE_conditions_table.csv /home/data_to_analyse/ /home/DIANA_mAP/data_out/ 4 ""

However I run into the following error:

>>>> INITIATING DIFFERENTIAL EXPRESSION ANALYSIS... 
Error in is.data.frame(x) : object 'master_table' not found
Calls: write.csv ... eval.parent -> eval -> eval -> write.table -> is.data.frame
Execution halted

The files are miRNA fastq files.

Any help would be great

**Comment by athalexiou** [comment]
Hi,

Does the rest of the analysis prior to the Differential Expression run properly? What is the log output prior to the error message?

From what I can understand by this error, something is wrong with reading all the individual sample quantification results and combining them into one single table, the "master_table".

If you are using different data from the example data provided, you should change the "example_DE_conditions_table.csv" to reflect the sample IDs of your data in the "samples" column as well as their appropriate condition. The DE analysis uses this "samples" column to find the sample quantification results and combine them into the master_table in order to invoke DESeq2.

Let me know if this helps.

Regards,
Thanos

**Comment by RNJ1993** [comment]
Hi,
thanks you for the reply and my apologies for my late response.

Yes, you were correct, the file "example_DE_conditions_table.tsv" had to be
modified to reflect the sample IDs of my data.

Thanks again
