### ISSUE TITLE
DIANA_mAP Error: subscript contains out-of-bounds indices

### ISSUE THREAD

**Issue by RNJ1993** [athalexiou/DIANA-mAP#3]
Hi,
When running DIANA_mAP with four fatq.gz files under two conditions I receive the following error:

ANALYSIS END TIME: Wed 22 Sep 2021 10:29:07 AM UTC
DE ANALYSIS START TIME: Wed 22 Sep 2021 10:29:07 AM UTC
>>>> INITIATING DIFFERENTIAL EXPRESSION ANALYSIS... 
converting counts to integer mode
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
>> PLOTTING PCA... 
>> PLOTTING MA-PLOT... 
>> EXTRACTING TOP RESULTS... 
Error: subscript contains out-of-bounds indices
Execution halted

Any ideas why this might be occurring? 
Thanks

**Comment by athalexiou** [comment]
Hello,

Can you check the file named "DE_full_results.csv" for the number of results/lines? 
It is possible your DE analysis returns less than 200 results and so when the script tries to isolate the top 100 and the bottom 100 it runs out of results.

Double check that your conditions and samples are configured correctly and that you are comparing what you want.

In order to fix this, you can open the "diana_map_multi.r" script, and search for line 149 which should write: "n = 100".
Change the number 100 to a lower number according to your total results number, save the script and run it again. (Remember this gets the top n and bottom n differentialy expressed results. So if you set n to 50, you would need to have at least 100 total results in the "DE_full_results.csv" file)

Regards,
Thanos

**Comment by RNJ1993** [comment]
Yes you were correct, my DE analysis returned ~ 160 results so this does
appear to be the reason for the error. Once I added in more samples the
error disappeared.

Thanks again for your help.
