### ISSUE TITLE
not such file in directory

### ISSUE THREAD

**Issue by dotcom-debug** [athalexiou/DIANA-mAP#5]
python dnapi.py -h
python2: can't open file 'dnapi.py': [Errno 2] No such file or directory

**Comment by athalexiou** [comment]
Hello,

DNApi is not automatically imported into the PATH environment variable. In order to find it and use it as a standalone, you have to navigate to the folder it was extracted.
If you are using DIANA-mAP standalone you have to provide that folder in the "path_dnapi" variable of the "diana_map_config.r" file.

If you are using the docker version, DNApi is located in the home/progs/DNApi folder of the docker image and the "diana_map_config.r" is already updated for you.

Thank you for using DIANA-mAP, let me know if you have any other issues.

Regards,
Thanos
